db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  privileged: true
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=demo
    - MYSQL_USER=demo_user
    - MYSQL_PASSWORD=demo_password

spring-boot:
  image: spring-boot:latest
  ports:
    - "8080:8083"
  links:
    - db:db
