spring.profiles: dev

server:
  address: 0.0.0.0
  port: 8082

---

spring.profiles: container

server:
  address: 0.0.0.0
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://db:3306/demo
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

flyway:
  enabled: true
  encoding: UTF-8
  url: jdbc:mysql://db:3306/demo
  user: root
  password: password
  sql-migration-prefix: V
  sql-migration-suffix: .sql
  locations: db/migration

hibernate:
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show_sql: true